[package]
name = "svg2pts"
version = "0.1.0"
authors = ["Thomas Dagenais <exrok@i64.dev>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
usvg = "^0.9"
lyon_geom = "^0.15"
ryu = "^1.0"